### ISSUE TITLE
Timing belt choice

### ISSUE THREAD

**Issue by lee7670** [MGX3D/Turntable#1]
Any reason you're using a GT2 Pulley and a MXL Belt for this?

**Comment by MGX3D** [comment]
Good catch :). This is more as a result of the parts I had on hand at the time. Turned out to work really well in practice though, after >1 year of use the wear on the belt turns out to be on the edge instead (caused by drift coming from the alignment of the pulley-tensioner-bearing). Using a matching MXL pulley here is definitely a better choice (a GT2 setup should work equally well, the bearing contact surface is large enough for the more rounded tooth profile to not matter).
